language: node_js
node_js:
  - "6"
  - "7"
env:
  global:
    - NODE_ENV=unittest
cache:
  directories:
    - node_modules
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database sequelize_slugify_test;' -U postgres
branches:
  only:
    - master
