language: node_js
node_js:
  - "6"
  - "8"
  - "10"
env:
  global:
    - NODE_ENV=unittest
cache: npm
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database sequelize_slugify_test;' -U postgres
script:
  - npm run lint
  - npm run test
branches:
  only:
    - master
